stages:
  - build

variables:
  GIT_STRATEGY: none
  IMAGE_NAMESPACE: frontend_utils
  IMAGE_NAME: nest_starter
  GIT_REPO_NAMESPACE: wangliguo
  GIT_REPO_NAME: nest_starter

before_script:
  - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD https://dockerhub.datagrand.com
  - git clone -b $CI_COMMIT_REF_NAME --depth=1 ssh://git@git.datagrand.com:58422/$GIT_REPO_NAMESPACE/$GIT_REPO_NAME.git
  - cd $GIT_REPO_NAME
  - export DATE=$(date +'%Y%m%d')
  - export IMAGE_TAG="ci"_$DATE"_"${CI_COMMIT_SHA:0:7}
  - export IMAGE=dockerhub.datagrand.com/$IMAGE_NAMESPACE/$IMAGE_NAME:$IMAGE_TAG

build:
  stage: build
  image: dockerhub.datagrand.com/ci_runner/frontend_web:1.0-taobao
  retry: 2
  script:
    - docker build -t $IMAGE -f Dockerfile .
    - docker push $IMAGE
    - echo 'IMAGE:' $IMAGE
  allow_failure: false
